### ISSUE TITLE
intlDate/formatDate fails on IE8 when passing in ISO date format

### ISSUE THREAD

**Issue by ktslwy** [yahoo/dust-intl#38]
On IE8, [this call](https://github.com/yahoo/dust-helper-intl/blob/master/dist/dust-intl.js#L2327) returns `NaN` for ISO date format. The call is made as `new Date('2014-09-19T20:37:21Z').getTime()`. It seems IE8 does not recognize this format, while newer IE and other browsers work for these. I would expect a polyfill to handle this case.

**Comment by ericf** [comment]
We're not going to change or add the date parsing features built into the runtime. If IE8 can't parse the ISO string into a valid `Date` instance, then it won't work. If you're stuck with ISO dates in your DB or something, then you might want to find a lib that can parse them into valid `Date` instances before passing them o the helper.
